# Generated by Django 4.2.23 on 2025-08-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymeasurement',
            name='high_hip',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
