# Generated by Django 4.2.23 on 2025-08-19 15:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_bodymeasurement_high_hip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodymeasurement',
            options={'ordering': ['-updated_at'], 'verbose_name': 'اندازه\u200cگیری بدن', 'verbose_name_plural': 'اندازه\u200cگیری\u200cهای بدن'},
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 19, 15, 58, 50, 295375, tzinfo=datetime.timezone.utc), verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='body_type',
            field=models.CharField(blank=True, choices=[('HOURGLASS', 'ساعت\u200cشنی'), ('RECTANGLE', 'مستطیل'), ('TRIANGLE', 'مثلث (گلابی)'), ('INVERTED_TRIANGLE', 'مثلث وارونه (سیب)'), ('APPLE', 'گرد (سیب)'), ('OTHER', 'سایر')], max_length=20, null=True, verbose_name='تیپ بدنی'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='bust',
            field=models.FloatField(blank=True, null=True, verbose_name='دور سینه (سانتی\u200cمتر)'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='قد (سانتی\u200cمتر)'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='high_hip',
            field=models.FloatField(blank=True, help_text='حدود ۱۰ سانت زیر کمر', null=True, verbose_name='دور بالای باسن (سانتی\u200cمتر)'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='hips',
            field=models.FloatField(blank=True, null=True, verbose_name='دور باسن (سانتی\u200cمتر)'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bodymeasurement', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='waist',
            field=models.FloatField(blank=True, help_text='مقدار باید بالای ناف و زیر دنده\u200cها اندازه\u200cگیری شود', null=True, verbose_name='دور کمر (سانتی\u200cمتر)'),
        ),
    ]
