# Generated by Django 4.2.23 on 2025-08-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_bodymeasurement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymeasurement',
            name='body_type',
            field=models.CharField(blank=True, choices=[('HOURGLASS', 'ساعت\u200cشنی'), ('RECTANGLE', 'مستطیل'), ('TRIANGLE', 'مثلث (گلابی)'), ('INVERTED_TRIANGLE', 'مثلث وارونه'), ('APPLE', 'گرد (سیب)')], max_length=20, null=True, verbose_name='تیپ بدنی'),
        ),
    ]
