# Generated by Django 4.2.23 on 2025-08-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='body_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='generated_image',
            field=models.ImageField(blank=True, null=True, upload_to='previews/'),
        ),
    ]
