# Generated by Django 4.2.23 on 2025-08-19 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_alter_measurement_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='arm_length',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='arm_width',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='breast_shape',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='generated_image',
        ),
    ]
