# Generated by Django 4.2.23 on 2025-08-28 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendation', '0004_remove_measurement_arm_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='created_at',
        ),
        migrations.AddField(
            model_name='measurement',
            name='arm_length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='arm_width',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='breast_shape',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='bust',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='hips',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='waist',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='generated_images/')),
                ('prompt', models.TextField()),
                ('body_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sleeve', models.CharField(blank=True, max_length=50, null=True)),
                ('neckline', models.CharField(blank=True, max_length=50, null=True)),
                ('bodice', models.CharField(blank=True, max_length=50, null=True)),
                ('skirt', models.CharField(blank=True, max_length=50, null=True)),
                ('train', models.CharField(blank=True, max_length=50, null=True)),
                ('structure', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
