# Generated by Django 4.2.23 on 2025-08-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='day_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
